// C:\Users\User\hume-voice-simulator\lib\utils.ts
export function cn(...classes: (string | undefined | false | null)[]) {
  return classes.filter(Boolean).join(" ");
}

export function generateUUID() {
  return crypto.randomUUID(); // built-in in Node 16+
}

export const getRandomMedicalQuote = () => {
  const quotes = [
  { text: "“Wherever the art of medicine is loved, there is also a love of humanity.”", author: "— Hippocrates" },
  { text: "“The good physician treats the disease; the great physician treats the patient who has the disease.”", author: "— William Osler" },
  { text: "“Medicine is a science of uncertainty and an art of probability.”", author: "— William Osler" },
  { text: "“The art of medicine consists of amusing the patient while nature cures the disease.”", author: "— Voltaire" },
  { text: "“It is health that is real wealth and not pieces of gold and silver.”", author: "— Mahatma Gandhi" },
  { text: "“The physician's highest calling, his only calling, is to make sick people healthy - to heal, as it is termed.”", author: "— Samuel Hahnemann" },
  { text: "“The best doctor gives the least medicines.”", author: "— Benjamin Franklin" },
  { text: "“Prevention is better than cure.”", author: "— Desiderius Erasmus" },
  { text: "“Innovation distinguishes between a leader and a follower.”", author: "— Steve Jobs" },
  { text: "“The future of medicine is not just in treating illness but in predicting and preventing it.”", author: "— Eric Topol" },
  { text: "“Artificial intelligence will not replace doctors, but doctors who use AI will replace those who do not.”", author: "— Bertalan Meskó" },
  { text: "“Digital health is not about technology, it’s about people.”", author: "— Paul Sonnier" },
  { text: "“The patient is the most underused person in healthcare.”", author: "— Dave deBronkart (e-Patient Dave)" },
  { text: "“Technology will never replace physicians, but physicians using technology will replace those who don’t.”", author: "— Daniel Kraft" },
  { text: "“Robotics and AI are changing surgery from art to precision.”", author: "— Atul Gawande" },
  { text: "“Medicine is moving from reactive to proactive, from generalized to personalized.”", author: "— Leroy Hood" },
  { text: "“Wearable technology will transform how we live and how we heal.”", author: "— Ray Kurzweil" },
  { text: "“Big data in healthcare means big responsibility.”", author: "— Margaret Chan" },
  { text: "“Telemedicine is not the future of medicine, it is the present.”", author: "— Thomas R. Insel" },
  { text: "“AI is the new stethoscope.”", author: "— Eric Topol" },
  { text: "“Precision medicine is the key to unlocking better, faster, and safer treatments.”", author: "— Francis Collins" },
  { text: "“Innovation in medicine should always serve compassion, not just computation.”", author: "— Devi Shetty" },
  { text: "“Healthcare technology is not about replacing human touch, but enhancing it.”", author: "— Fei-Fei Li" },
  { text: "“Data will save lives, but only if we know how to listen to it.”", author: "— Atul Butte" },
  { text: "“The marriage of technology and empathy defines modern medicine.”", author: "— Victor Dzau" },
  { text: "“Digital transformation in healthcare begins with trust.”", author: "— Judy Faulkner" },
  { text: "“Machine learning is medicine’s new microscope.”", author: "— Andrew Ng" },
  { text: "“Every patient should have access to their own health data in real time.”", author: "— John Halamka" },
  { text: "“3D printing is redefining what’s possible in surgery.”", author: "— Anthony Atala" },
  { text: "“Virtual reality will train the next generation of healers.”", author: "— Daniel Kraft" },
  { text: "“In the digital era, compassion must evolve alongside innovation.”", author: "— Vivek Murthy" },
  { text: "“Technology should empower doctors to be more human, not less.”", author: "— Toby Cosgrove" },
  { text: "“Genomics is giving medicine a deeper language to read life.”", author: "— Jennifer Doudna" },
  { text: "“AI in healthcare is not magic—it’s mathematics serving humanity.”", author: "— Peter Lee" },
  { text: "“The best technology disappears into the background of good care.”", author: "— Eric Dishman" },
  { text: "“Virtual care extends the reach of empathy beyond walls.”", author: "— Seema Verma" },
  { text: "“When data meets medicine, miracles happen.”", author: "— Bernard Meyerson" },
  { text: "“Healthcare innovation fails when it forgets the patient.”", author: "— Don Berwick" },
  { text: "“Digital health will succeed only when it feels personal.”", author: "— Susannah Fox" },
  { text: "“The stethoscope of tomorrow listens to your data.”", author: "— Daniel Kraft" },
  { text: "“Medicine and technology share a goal—to make life longer and better.”", author: "— Robert Wachter" },
  { text: "“Nothing in life is to be feared; it is only to be understood.”", author: "— Marie Curie" },
  { text: "“Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.”", author: "— Albert Einstein" },
  { text: "“Intelligence is the ability to adapt to change.”", author: "— Stephen Hawking" },
  { text: "“Science knows no country, because knowledge belongs to humanity.”", author: "— Louis Pasteur" },
  { text: "“It is not the strongest of the species that survives, nor the most intelligent, but the one most responsive to change.”", author: "— Charles Darwin" },
  { text: "“A doctor who can’t imagine the pain of his patient is no doctor at all.”", author: "— Ben Carson" },
  { text: "“The reward of the scientist is the discovery itself, and the joy of understanding something no one ever knew before.”", author: "— Erwin Schrödinger" },
  { text: "“Science and everyday life cannot and should not be separated.”", author: "— Rosalind Franklin" },
  { text: "“Our greatest responsibility is to be good ancestors.”", author: "— Jonas Salk" },
  { text: "“Medicine is a science of experience; its books are not its foundation, but its tools.”", author: "— Paracelsus" },
  { text: "“To cure sometimes, to relieve often, to comfort always.”", author: "— Edward Livingston Trudeau" },
  { text: "“The good physician knows how to cure; the great one knows how to care.”", author: "— Carl Jung" },
  { text: "“Science gives us the tools; humanity gives us the reason.”", author: "— Neil deGrasse Tyson" },
  { text: "“Technology is best when it brings people together.”", author: "— Matt Mullenweg" },
  { text: "“In science, the credit goes to the man who convinces the world, not the man to whom the idea first occurs.”", author: "— Francis Darwin" },
  { text: "“Every brilliant experiment, like every great work of art, starts with an act of imagination.”", author: "— Jonah Lehrer" },
  { text: "“Science is organized knowledge. Wisdom is organized life.”", author: "— Immanuel Kant" },
  { text: "“The advancement of medicine lies not in more machines but in deeper empathy.”", author: "— Abraham Verghese" },
  { text: "“Courage is the price that life exacts for granting peace.”", author: "— Amelia Earhart" },
  { text: "“A good surgeon knows how to operate, a better one when to operate, and the best when not to operate.”", author: "— Harvey Cushing" },
  { text: "“Science is the acceptance of what works and the rejection of what does not.”", author: "— Jacob Bronowski" },
  { text: "“The art of healing comes from nature, not from the physician.”", author: "— Paracelsus" },
  { text: "“In nothing do men more nearly approach the gods than in giving health to men.”", author: "— Cicero" },
  { text: "“The most exciting phrase in science is not ‘Eureka!’ but ‘That’s funny...’”", author: "— Isaac Asimov" },
  { text: "“To study medicine is to learn the language of life.”", author: "— Anonymous" },
  { text: "“AI will not make doctors obsolete—it will make medicine more human.”", author: "— Fei-Fei Li" },
  { text: "“We are at the dawn of a new age where biology and technology merge.”", author: "— Craig Venter" },
  { text: "“Science is not only a discipline of reason but also of romance and passion.”", author: "— Stephen Hawking" },
  { text: "“Innovation is seeing what everybody has seen and thinking what nobody has thought.”", author: "— Albert Szent-Györgyi" },
  { text: "“Progress is born of curiosity and compassion combined.”", author: "— Peter Diamandis" },
  { text: "“Good science and good care both begin with listening.”", author: "— Atul Gawande" }
];
  return quotes[Math.floor(Math.random() * quotes.length)];
};